/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lv_lumii_tda_util_ParentProcessWaiter */

#ifndef _Included_lv_lumii_tda_util_ParentProcessWaiter
#define _Included_lv_lumii_tda_util_ParentProcessWaiter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lv_lumii_tda_util_ParentProcessWaiter
 * Method:    waitForTheParentProcessToTerminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lv_lumii_tda_util_ParentProcessWaiter_waitForTheParentProcessToTerminate
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
