// Automatically generated by StubsGenerator.java

#ifndef TDAKERNEL_STUB_PIPE_H
#define TDAKERNEL_STUB_PIPE_H

#include "tdakernel_stub_base.h"

class PipeStub : public StubBase {
  void* hTDAPipedProcess;
public:
  PipeStub(void* _hTDAPipedProcess);
  virtual /*override*/ void close();
  virtual /*override*/ bool exists(const char* param1);
  virtual /*override*/ bool open(const char* param1);
  virtual /*override*/ bool startSave();
  virtual /*override*/ bool cancelSave();
  virtual /*override*/ bool finishSave();
  virtual /*override*/ bool drop(const char* param1);
  virtual /*override*/ __int64 findClass(const char* param1);
  virtual /*override*/ const char* getClassName(__int64 param1);
  virtual /*override*/ __int64 createObject(__int64 param1);
  virtual /*override*/ __int64 createClass(const char* param1);
  virtual /*override*/ bool deleteClass(__int64 param1);
  virtual /*override*/ bool isClass(__int64 param1);
  virtual /*override*/ bool isDirectSubClass(__int64 param1, __int64 param2);
  virtual /*override*/ bool deleteObject(__int64 param1);
  virtual /*override*/ bool moveObject(__int64 param1, __int64 param2);
  virtual /*override*/ bool isTypeOf(__int64 param1, __int64 param2);
  virtual /*override*/ bool isKindOf(__int64 param1, __int64 param2);
  virtual /*override*/ __int64 createAttribute(__int64 param1, const char* param2, __int64 param3);
  virtual /*override*/ bool isDerivedClass(__int64 param1, __int64 param2);
  virtual /*override*/ __int64 findAttribute(__int64 param1, const char* param2);
  virtual /*override*/ bool deleteAttribute(__int64 param1);
  virtual /*override*/ const char* getAttributeName(__int64 param1);
  virtual /*override*/ const char* getPrimitiveDataTypeName(__int64 param1);
  virtual /*override*/ __int64 findPrimitiveDataType(const char* param1);
  virtual /*override*/ bool isPrimitiveDataType(__int64 param1);
  virtual /*override*/ __int64 getIteratorForClasses();
  virtual /*override*/ const char* getAttributeValue(__int64 param1, __int64 param2);
  virtual /*override*/ __int64 createAssociation(__int64 param1, __int64 param2, const char* param3, const char* param4, bool param5);
  virtual /*override*/ __int64 getIteratorForDirectSubClasses(__int64 param1);
  virtual /*override*/ __int64 getIteratorForAllClassObjects(__int64 param1);
  virtual /*override*/ __int64 getIteratorForDirectAttributes(__int64 param1);
  virtual /*override*/ __int64 getAttributeDomain(__int64 param1);
  virtual /*override*/ bool deleteGeneralization(__int64 param1, __int64 param2);
  virtual /*override*/ bool createGeneralization(__int64 param1, __int64 param2);
  virtual /*override*/ bool excludeObjectFromClass(__int64 param1, __int64 param2);
  virtual /*override*/ __int64 getIteratorForAllAttributes(__int64 param1);
  virtual /*override*/ bool includeObjectInClass(__int64 param1, __int64 param2);
  virtual /*override*/ __int64 getIteratorForDirectSuperClasses(__int64 param1);
  virtual /*override*/ __int64 getIteratorForDirectClassObjects(__int64 param1);
  virtual /*override*/ bool setAttributeValue(__int64 param1, __int64 param2, const char* param3);
  virtual /*override*/ bool deleteAttributeValue(__int64 param1, __int64 param2);
  virtual /*override*/ __int64 getIteratorForDirectLinguisticInstances(__int64 param1);
  virtual /*override*/ __int64 getIteratorForDirectObjectClasses(__int64 param1);
  virtual /*override*/ __int64 getIteratorForObjectsByAttributeValue(__int64 param1, const char* param2);
  virtual /*override*/ __int64 getIteratorForAllOutgoingAssociationEnds(__int64 param1);
  virtual /*override*/ __int64 getIteratorForDirectIngoingAssociationEnds(__int64 param1);
  virtual /*override*/ __int64 getIteratorForAllLinguisticInstances(__int64 param1);
  virtual /*override*/ __int64 getIteratorForDirectOutgoingAssociationEnds(__int64 param1);
  virtual /*override*/ __int64 getIteratorForAllIngoingAssociationEnds(__int64 param1);
  virtual /*override*/ __int64 resolveIterator(__int64 param1, int param2);
  virtual /*override*/ const char* getRoleName(__int64 param1);
  virtual /*override*/ bool deleteLink(__int64 param1, __int64 param2, __int64 param3);
  virtual /*override*/ bool createLink(__int64 param1, __int64 param2, __int64 param3);
  virtual /*override*/ bool isLinguistic(__int64 param1);
  virtual /*override*/ __int64 getAttributeType(__int64 param1);
  virtual /*override*/ __int64 getTargetClass(__int64 param1);
  virtual /*override*/ bool isAssociationEnd(__int64 param1);
  virtual /*override*/ void freeReference(__int64 param1);
  virtual /*override*/ bool isAttribute(__int64 param1);
  virtual /*override*/ __int64 getSourceClass(__int64 param1);
  virtual /*override*/ bool linkExists(__int64 param1, __int64 param2, __int64 param3);
  virtual /*override*/ bool isComposition(__int64 param1);
  virtual /*override*/ void freeIterator(__int64 param1);
  virtual /*override*/ __int64 getLinguisticClassFor(__int64 param1);
  virtual /*override*/ bool deleteAssociation(__int64 param1);
  virtual /*override*/ bool createOrderedLink(__int64 param1, __int64 param2, __int64 param3, int param4);
  virtual /*override*/ __int64 deserializeReference(const char* param1);
  virtual /*override*/ __int64 createDirectedAssociation(__int64 param1, __int64 param2, const char* param3, bool param4);
  virtual /*override*/ bool isAdvancedAssociation(__int64 param1);
  virtual /*override*/ __int64 resolveIteratorFirst(__int64 param1);
  virtual /*override*/ const char* callSpecificOperation(const char* param1, const char* param2);
  virtual /*override*/ __int64 getInverseAssociationEnd(__int64 param1);
  virtual /*override*/ int getLinkedObjectPosition(__int64 param1, __int64 param2, __int64 param3);
  virtual /*override*/ int getIteratorLength(__int64 param1);
  virtual /*override*/ __int64 getIteratorForLinkedObjects(__int64 param1, __int64 param2);
  virtual /*override*/ __int64 createAdvancedAssociation(const char* param1, bool param2, bool param3);
  virtual /*override*/ __int64 getIteratorForLinguisticClasses();
  virtual /*override*/ __int64 findAssociationEnd(__int64 param1, const char* param2);
  virtual /*override*/ const char* serializeReference(__int64 param1);
  virtual /*override*/ __int64 resolveIteratorNext(__int64 param1);
  virtual /*override*/ ~PipeStub();
}; // class PipeStub

#endif // TDAKERNEL_STUB_PIPE_H
