package lv.lumii.tda.raapi;


/**
* Adapted automatically from lv/lumii/tda/kernel/corba/IRepository.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/webAppOS/build/prebuild_raapi/raapi.idl
* Friday, April 6, 2018 12:22:20 PM EEST
*/


/**
 * The <code>IRepository</code> interface is a union of
 * <code>RAAPI</code> containing operations on model elements
 * and <code>IRepositoryManagement</code> containing
 * technical operations on repositories such as operations
 * for opening, closing, saving, etc.
 ***/
public interface IRepository  extends lv.lumii.tda.raapi.IRepositoryManagement, lv.lumii.tda.raapi.RAAPI
{
} // interface IRepository
